#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bookmng?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#
#mybatis.mapper-locations: classpath:mapper/*.xml

server:
  port: 8002
  servlet:
    contextPath: /acts/book-mng
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/bookmng?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 3
    minimumIdle: 1
    connectionTestQuery: SELECT 1
    pool-name: AppPool
    auto-commit: true
    initialization-mode: always
    platform: mysql
  aop:
    proxy-target-class: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
cors:
  accessControlAllowOrigin: http://localhost:4200
  accessControlAllowHeaders: Content-Type
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.mybatis: DEBUG
mybatis:
  mapper-locations: com/example/accenturespringbootdemo/repository/*.xml